name: nf-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "25.04.6"
        TEST_FILE:
          - tests/modules/split_transcript_counts.nf.test
          - tests/modules/vcf_expression_annotator.nf.test
          - tests/modules/clean_vcf.nf.test
          - tests/modules/vcf_to_csv.nf.test
          - tests/main.nf.test

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        env:
          NXF_VER: ${{ matrix.NXF_VER }}
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
          nextflow -version

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1

      - name: Run nf-test
        run: |
          mkdir -p reports
          nf-test test ${{ matrix.TEST_FILE }} --profile test,docker --verbose --tap reports/test-results-${{ strategy.job-index }}.tap